### ISSUE TITLE
[対応済み-解決済み]: LINEがクラッシュする

### ISSUE THREAD

**Issue by atuy1219** [areteruhiro/LIMEs#14]
### LSPatch 使用の有無

- [X] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

LINEを開くと一瞬だけ起動しますがその後クラッシュします

### 再現する手順

今朝、通知が来ている状態でLINEを開くとクラッシュします

一度LIMEをオフにしてから既読を付けて、もう一度LIMEをオンにして開くとクラッシュしませんでした
その後通知が来てもクラッシュしませんでした

昨日も通知が来ている状態でクラッシュはしませんでした

なので現状は困っていないです
ですが一応クラッシュログを貼っておきます
[crash-jp-naver-line-android-10_11-10-37-32_744.zip](https://github.com/user-attachments/files/17689877/crash-jp-naver-line-android-10_11-10-37-32_744.zip)
[crash-jp-naver-line-android-10_11-10-38-10_282.zip](https://github.com/user-attachments/files/17689878/crash-jp-naver-line-android-10_11-10-38-10_282.zip)
[crash-jp-naver-line-android-10_11-10-40-16_001.zip](https://github.com/user-attachments/files/17689879/crash-jp-naver-line-android-10_11-10-40-16_001.zip)

### 有効にしている LIME の設定

VOOM アイコンを削除, ウォレットアイコンを削除, ニュースまたは通話アイコンを削除, ボトムバーのアイコンを均等に配置, ボトムバーのアイコンのラベルを削除, 広告を削除, おすすめを削除, LYP プレミアムのおすすめを削除, サービスのラベルを削除, 通知から "通知オフ" アクションを削除, WebView を規定のブラウザにリダイレクト, 常に既読をつけない, トーク画面右上のメニューにある「未読のまま閲覧」のスイッチを削除, トラッキング通信をブロック, LINE バージョンの確認を停止

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by atuy1219** [comment]
追記:有効にしている LIME の設定が複数選択できません

**Comment by areteruhiro** [comment]
> 追記:有効にしている LIME の設定が複数選択できません

どういう状態ですか？？
選択できない or 動作しない（機能しない）

**Comment by areteruhiro** [comment]
なんか、line 14.18.1で仕様変更されてるんですよね。
対応できるまで、
対応バージョンさげてるバージョンアップロードしましょうか？

**Comment by areteruhiro** [comment]
一応、少し心当たりあるのでそれ、一度訂正しますね

**Comment by areteruhiro** [comment]
機能していない場合、それが、トリガーとしてエラーが発生してる可能性があります。

**Comment by atuy1219** [comment]
> > 追記:有効にしている LIME の設定が複数選択できません
> 
> どういう状態ですか？？ 選択できない or 動作しない（機能しない）

誤解させてしまってすみません githubのIssueでの話です
言葉足らずでした

**Comment by areteruhiro** [comment]
あーなるほど笑了解です

**Comment by areteruhiro** [comment]
修正しましたややこしいので消しておきますねすみません

**Comment by areteruhiro** [comment]
クラッシュさせるコードを無効化させる、コードを1.13.1aで追加しました。

これで治るかはわかりませんが様子をみてください。、

**Comment by atuy1219** [comment]
わかりました。
何かあったらまたご連絡します

**Comment by atuy1219** [comment]
またクラッシュしました…
今回は通知も来ていない状態ですね
例のごとく、LIMEをオフにしてからオンにするともとに戻りました

ただ、クラッシュログをみる限りは前回とは別の原因っぽいです（~ぬるぽ~）

```
FATAL EXCEPTION: [LINE] #4 Tf.c$a
Process: jp.naver.line.android, PID: 2206
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at LSPHooker_.f(Unknown Source:24)
	at fb1.c.f(Unknown Source:7)
	at we1.b.f(Unknown Source:25)
	at we1.b.n(Unknown Source:0)
	at org.apache.thrift.l.a(Unknown Source:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(SourceFile:82)
	at LSPHooker_.a(Unknown Source:14)
	at jp.naver.line.android.thrift.client.impl.LegacyTalkServiceClientImpl.S2(Unknown Source:28)
	at Ka1.f$d.f(Unknown Source:27)
	at Tf.c$a.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at jp.naver.line.android.util.q$a.c(Unknown Source:47)
	at jp.naver.line.android.util.q$a.run(Unknown Source:31)
	at java.lang.Thread.run(Thread.java:1012)


やはり対応バージョン下げたのを頂いたほうがよいかもしれません…

**Comment by areteruhiro** [comment]
どういう条件の時にクラッシュしますか？

**Comment by areteruhiro** [comment]
キャッシュ削除してみてくれますか？

**Comment by areteruhiro** [comment]
送信取り消し無効 機能をオンにしていますか？

**Comment by atuy1219** [comment]
> どういう条件の時にクラッシュしますか？

条件は突然クラッシュが起きたのでわからないです

>どの、機能をオンにしていますか？

VOOM アイコンを削除, ウォレットアイコンを削除, ニュースまたは通話アイコンを削除, ボトムバーのアイコンを均等に配置, ボトムバーのアイコンのラベルを削除, 広告を削除, おすすめを削除, LYP プレミアムのおすすめを削除, サービスのラベルを削除,  更新されたプロフィールを削除, 通知から "通知オフ" アクションを削除, WebView を規定のブラウザにリダイレクト, 常に既読をつけない, 送信したメッセージの既読者の確認, 「未読のまま閲覧」のスイッチを削除, トラッキング通信をブロック, LINE バージョンの確認を停止, LsPatch用 着信音を鳴らす

> 送信取り消し無効 機能をオンにしていますか？

していないです

**Comment by areteruhiro** [comment]
更新されたプロフィールを削除、常に既読をつけない
を、無効にしたら治る気がします。

**Comment by atuy1219** [comment]
承知しました
ありがとうございます

**Comment by hy906040** [comment]
割り込む形で失礼します。
同様のクラッシュが発生していましたがv1.13.1bを使用したら解決しました。
しかしLimeの設定ボタンが表示されない症状が発生しています。
設定自体は以前のバージョンで設定されたものが反映されているようです。
![Screenshot_20241111_050806_LINE](https://github.com/user-attachments/assets/c684f195-17b7-403a-9b41-7b5887385728)

**Comment by areteruhiro** [comment]
> 割り込む形で失礼します。
> 同様のクラッシュが発生していましたがv1.13.1bを使用したら解決しました。
> しかしLimeの設定ボタンが表示されない症状が発生しています。
> 設定自体は以前のバージョンで設定されたものが反映されているようです。
> ![Screenshot_20241111_050806_LINE](https://github.com/user-attachments/assets/c684f195-17b7-403a-9b41-7b5887385728)

LsPatchは何を使ってますか？？
https://github.com/JingMatrix/LSPatch/actions/runs/11766636912/artifacts/2168500049
これを、使ってもらっていいですか

**Comment by hy906040** [comment]
回答ありがとうございます。
指定いただいたLsPatchの使用に加えて強制終了→キャッシュクリアも実施が変化はありませんでした。

**Comment by areteruhiro** [comment]
adb shell を実行してから貼り付けてください。
while true; do logcat --pid=$(pidof -s org.lsposed.lspatch) '*':W; done

**Comment by areteruhiro** [comment]
> 割り込む形で失礼します。
> 同様のクラッシュが発生していましたがv1.13.1bを使用したら解決しました。
> しかしLimeの設定ボタンが表示されない症状が発生しています。
> 設定自体は以前のバージョンで設定されたものが反映されているようです。
> ![Screenshot_20241111_050806_LINE](https://github.com/user-attachments/assets/c684f195-17b7-403a-9b41-7b5887385728)


1.13.b以前だと表示されますか？？

**Comment by hy906040** [comment]
コマンド実施しましたがrange of [outとしかログが表示されないのですがなにか手順があるのでしょうか？](![Screenshot_20241111_070959_LINE](https://github.com/user-attachments/assets/7e5f0567-34f5-41d3-8497-d3352f11f8e3))
一応LsPatchとLineを強制終了→キャッシュクリア→コマンド実行→各アプリ起動(Lineは設定画面開くまで実施)しました。

v1.13.1aで再パッチしてインストールしてみたところ何故かクラッシュせずボタンも表示されるようになりました。

**Comment by hy906040** [comment]
コマンド実施しましたがrange of outとしかログが表示されないのですがなにか手順があるのでしょうか？
一応LsPatchとLineを強制終了→キャッシュクリア→コマンド実行→各アプリ起動(Lineは設定画面開くまで実施)しました。

v1.13.1aで再パッチしてインストールしてみたところ何故かクラッシュせずボタンも表示されるようになりました。
![Uploading Screenshot_20241111_070959_LINE.png…]()

**Comment by hy906040** [comment]
コマンド実施しましたがrange of outとしかログが表示されないのですがなにか手順があるのでしょうか？
一応LsPatchとLineを強制終了→キャッシュクリア→コマンド実行→各アプリ起動(Lineは設定画面開くまで実施)しました。

v1.13.1aで再パッチしてインストールしてみたところ何故かクラッシュせずボタンも表示されるようになりました。
![Screenshot_20241111_070959_LINE](https://github.com/user-attachments/assets/5dad2fb3-f7a5-4441-906d-1cd1382535d4)

**Comment by areteruhiro** [comment]
強制終了する原因は、データの初期化がうまくないかない
みたいな感じでエラーを吐いてるのかなとおもっています。
キャッシュ削除や、強制終了で治るとは思うのですが。

今回の1.13.bで、
クラッシュ対策として自動でキャッシュ削除をするコードを追加したので、キャッシュを削除したそれの影響かもしれません（LsPatchの影響か）

**Comment by hy906040** [comment]
前回のv1.13.1aパッチ適用時との違いは仰る通り直前にv1.13.1bを導入したこととLsPatchを更新したことです。
朝から対応ありがとうございました。

**Comment by hy906040** [comment]
v1.13.b_1_14.18.1を導入し、臨時キャッシュクリアの機能を使用したところ設定ボタンが表示されなくなりました。
あと誤記だと思うのですが対応バージョンが14.18.1になっていません。、

**Comment by areteruhiro** [comment]
ちょっと時間ないので、時間ある時に対応しますね。

**Comment by hy906040** [comment]
手が空いた時によろしくおねがいします。
一応弊環境ではv1.13.1aを再パッチしたところボタンは再表示されクラッシュしていないです。

**Comment by areteruhiro** [comment]
多分、どこかのタイミングで、また、14.18.1はクラッシュすると思います。（しなければそのままお使いください）

**Comment by areteruhiro** [comment]
lineのバージョンアップが原因ではなく、
こちら側のコード変更による、クラッシュの可能性ということですね。確認致します

**Comment by areteruhiro** [comment]
> 暇だったのでv1.13.1b_14.17.0を試してみましたがログインまではできるのですが途中でクラッシュして開けなくなりました。
> 過去のバージョンは問題なかったです。

強制終了、キャッシュ削除か、LIMEオフ→開く
LIME→ON
を試してもらえますか

**Comment by areteruhiro** [comment]
ログインしすぎると、数10分〜数時間ロックされるので気をつけてください

**Comment by hy906040** [comment]
指摘いただいた手順は実施済ですが改善しませんでした。
注意ありがとうございます。
それならば過去のバージョンに戻して更新を待たせていただきます。

**Comment by areteruhiro** [comment]
色々デバックしていただいていてありがとうございます。
V1.12.5 の場合、クラッシュなどは起きませんか？

**Comment by hy906040** [comment]
v1.12.5dでは問題ありません。

**Comment by areteruhiro** [comment]
こちらの、環境下では全く同じクラッシュ等は発生していないので、そちらのコードをベースに、現在追加している機能を追加していきます。
ありがとうございます。

**Comment by areteruhiro** [comment]
https://github.com/areteruhiro/LIME-beta-hiro/releases/edit/v1.12.5e
こちらためしていただけますか

**Comment by areteruhiro** [comment]
こちらでエラーがなければ、一度14.18.1 対応バージョンをリリースしなおします

**Comment by hy906040** [comment]
試してみましたが問題なさそうです！

**Comment by atuy1219** [comment]
私も今日1日使用しましたが、クラッシュはありませんでした

**Comment by areteruhiro** [comment]
その情報から原因が推測できましたので、
それを気をつけて
次のアップデートの方を進めていきます。

もし今後、クラッシュなどありましたら、お知らせ願います
