### ISSUE TITLE
[Bug]: LsPatch v1.14.1 トラッキングの無効を有効時にクラッシュする

### ISSUE THREAD

**Issue by hy906040** [areteruhiro/LIMEs#20]
### LSPatch 使用の有無

- [X] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

首題の通りローカルにてスコープし、しばらくLineを使用しているとクラッシュして起動できなくなります。(おそらく統合でも同様と思われます。

### 有効にしている LIME の設定

VOOM アイコンを削除, ウォレットアイコンを削除, ニュースまたは通話アイコンを削除, 広告を削除, おすすめを削除, LYP プレミアムのおすすめを削除, 通知から "通知オフ" アクションを削除, 常に既読をつけない, 送信取り消しを拒否, トーク画面右上のメニューにある「未読のまま閲覧」のスイッチを削除, トラッキング通信をブロック, LINE バージョンの確認を停止

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by areteruhiro** [comment]
通信内容をログに出力 (開発者用)
を、オフにして試せますか。

**Comment by hy906040** [comment]
通信内容をログに出力(開発者用)オフでした。
誤記失礼しました。

**Comment by areteruhiro** [comment]
他に有効な機能はありますか？

**Comment by areteruhiro** [comment]
トラッキング機能も無効ですか？

**Comment by areteruhiro** [comment]
しばらくと言うと、30分以上ですか？
再現性のために、どれくらい利用しているとクラッシュするか教えていただきたいです

**Comment by hy906040** [comment]
30分以上は問題なく動作しています。
1日程度経過した際にクラッシュして起動しなくなる症状が2度発生しています。
トークフォルダーのグループ選択またはトークグループを開こうとした時にクラッシュが発生するようになっているような気がします。

**Comment by hy906040** [comment]
承知いたしました。
対応ありがとうございます。

**Comment by areteruhiro** [comment]
https://github.com/areteruhiro/LIME-beta-hiro/releases/tag/v1.14.1a
を利用してみてください、LsPatchで動作確認できていないので、保存されるかどうかも教えてください

**Comment by hy906040** [comment]
ボタンの動作は問題なさそうです。
ただUIで気になる点がありました
①ブラックのテーマを利用しているとオフ時のボタンがわかりにくい、色を変更した方が良い？
②私の端末だとボタンがインカメラの位置と被る、位置を左か右に変更した方が良い？
![Screenshot_20241129_185421_LINE](https://github.com/user-attachments/assets/b67ba385-44aa-4518-8d55-af2ccf5862ca)
![Screenshot_20241129_185435_LINE](https://github.com/user-attachments/assets/4ac66d0f-fa33-43fc-a252-a07f591e3a6d)

**Comment by areteruhiro** [comment]
https://github.com/areteruhiro/LIME-beta-hiro/releases/tag/v1.14.1b
すみません、修正必要だったのでリリースしなおしました

**Comment by areteruhiro** [comment]
白色の所がボタンなので分かりにくいとかはないのかなとは、個人的には思っています。

画像を利用すると、不具合の原因にもなりうるので、LsPatchはできる限りシンプルなコードで構成しています。

**Comment by hy906040** [comment]
位置変更は難しいのですね…残念です…
例えばですがオフは赤、オンは緑とかだとどのテーマでも視認性高まりませんかね？

**Comment by areteruhiro** [comment]
一応、バグ報告でのissueですので、 #21 で、それは話しましょう。

**Comment by areteruhiro** [comment]
一応、LsPatchで再現してみますね。

**Comment by atuy1219** [comment]
私も常に既読をつけないをオンにしていたところ以下のようなクラッシュが発生しました
何かのためになるかもしれないので貼っときます

```
FATAL EXCEPTION: [LINE] #4 Zf.c$a
Process: jp.naver.line.android, PID: 25910
java.lang.IllegalStateException: receiveSource is not set.
	at cj.b.f(Unknown Source:33)
	at Cd1.c.f(Unknown Source:7)
	at Tg1.b.f(Unknown Source:25)
	at Tg1.b.n(Unknown Source:0)
	at org.apache.thrift.l.a(Unknown Source:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(SourceFile:82)
	at LSPHooker_.a(Unknown Source:14)
	at jp.naver.line.android.thrift.client.impl.LegacyTalkServiceClientImpl.S2(Unknown Source:28)
	at hd1.f$d.f(Unknown Source:27)
	at Zf.c$a.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at jp.naver.line.android.util.p$a.c(Unknown Source:47)
	at jp.naver.line.android.util.p$a.run(Unknown Source:31)
	at java.lang.Thread.run(Thread.java:1012)
```


「常に既読をつけない」だと、LIME導入した端末側でも通知バッチが消えないので、どの人に対して未読なのかが分かりやすいのですが、「『未読のまま閲覧』スイッチ」だと通知バッチが端末側で見れなくなってしまうのはどうしようもないのでしょうか？

**Comment by areteruhiro** [comment]
なんかこれも以前見たことのあるエラーですねぇ、、

**Comment by areteruhiro** [comment]
なんかこれも以前見たことのあるエラーですねぇ、、

**Comment by areteruhiro** [comment]
通知バッチというのは、本体のホームランチャーでの話ですか？

**Comment by areteruhiro** [comment]
環境はLSPatchですか？
@atuy1219

**Comment by atuy1219** [comment]
> 通知バッチというのは、本体のホームランチャーでの話ですか？

トーク画面で見れるやつですね 誤解させてしまって申し訳ないです

>環境はLSPatchですか？

lspatchのローカルで使用してます

**Comment by areteruhiro** [comment]
> > 通知バッチというのは、本体のホームランチャーでの話ですか？
> 
> トーク画面で見れるやつですね 誤解させてしまって申し訳ないです
> 
> >環境はLSPatchですか？
> 
> lspatchのローカルで使用してます

未読スイッチ消えるの、未読が有効になってないですね、、、
修正します。

**Comment by areteruhiro** [comment]
対応しました

**Comment by areteruhiro** [comment]
https://github.com/areteruhiro/LIME-beta-hiro/actions/runs/12092661818
クラッシュ対策はコチラでしています。

**Comment by areteruhiro** [comment]
2a リリースしています、こちらで、試していただけますか。

**Comment by areteruhiro** [comment]
> 私も常に既読をつけないをオンにしていたところ以下のようなクラッシュが発生しました
> 何かのためになるかもしれないので貼っときます
> ```
> FATAL EXCEPTION: [LINE] #4 Zf.c$a
> Process: jp.naver.line.android, PID: 25910
> java.lang.IllegalStateException: receiveSource is not set.
> 	at cj.b.f(Unknown Source:33)
> 	at Cd1.c.f(Unknown Source:7)
> 	at Tg1.b.f(Unknown Source:25)
> 	at Tg1.b.n(Unknown Source:0)
> 	at org.apache.thrift.l.a(Unknown Source:2)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
> 	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(SourceFile:82)
> 	at LSPHooker_.a(Unknown Source:14)
> 	at jp.naver.line.android.thrift.client.impl.LegacyTalkServiceClientImpl.S2(Unknown Source:28)
> 	at hd1.f$d.f(Unknown Source:27)
> 	at Zf.c$a.run(Unknown Source:4)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at jp.naver.line.android.util.p$a.c(Unknown Source:47)
> 	at jp.naver.line.android.util.p$a.run(Unknown Source:31)
> 	at java.lang.Thread.run(Thread.java:1012)
> ```


こちらの、エラー対策は一応してみました。

**Comment by atuy1219** [comment]
今のところはクラッシュしていないので、様子をみてみます

**Comment by areteruhiro** [comment]
よろしくお願いいたします。
未読のままスイッチ、自体は正常に機能していますか

**Comment by atuy1219** [comment]
機能しています ありがとうございます

**Comment by areteruhiro** [comment]
logfoxで、ログ出力できないかこちらでも試してみます

**Comment by areteruhiro** [comment]
https://github.com/JingMatrix/LSPosed
をインストールして

Log Foxで、`LSPosed-Bridge`と、入力してください。
![Screenshot_20241201-091911.png](https://github.com/user-attachments/assets/7dfc3a31-a571-439e-9cb1-686eae0e5aeb)

**Comment by areteruhiro** [comment]
次クラッシュしたとき試してください

**Comment by hy906040** [comment]
2aと指示いただいたLsPatch使用、常に既読をつけないオフ、未読のまま閲覧スイッチオンの状況でクラッシュが発生しました。
次回発生時確認します。

**Comment by areteruhiro** [comment]
前回と同じで、一度クラッシュしたら、キャッシュ削除などしないと開けないですか？

**Comment by areteruhiro** [comment]
トラッキング通信をブロック
を、無効化すると改善されたという報告があります

**Comment by hy906040** [comment]
前回と同じくモジュールのスコープを外して通常状態で起動→再スコープで起動できるようになりました。
ではトラッキング通信をブロックをオフにしてみます。

**Comment by areteruhiro** [comment]
違うやり方で、トラッキングを無効化するようにしてみますね（改善されるかわかりませんが）

**Comment by atuy1219** [comment]
同じく、2aで 常に既読を付けない オフ、既読スイッチ オンの状況で前回と同様のエラーが発生しました
キャッシュ削除も効果がなく、再スコープすることで解消しました
私も トラッキングを無効化 をオフにした状態で様子をみてみます

**Comment by akir45** [comment]
私も2aでLsPatch使用、常に既読をつけないオフ、未読のまま閲覧スイッチオン、トラッキング無効化をオンでクラッシュしました。
一応クラッシュログ貼っておきます。

```
java.lang.IllegalStateException: receiveSource is not set.
	at cj.b.f(Unknown Source:33)
	at Cd1.c.f(Unknown Source:7)
	at Tg1.b.f(Unknown Source:25)
	at Tg1.b.n(Unknown Source:0)
	at org.apache.thrift.l.a(Unknown Source:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:158)
	at LSPHooker_.a(Unknown Source:14)
	at jp.naver.line.android.thrift.client.impl.LegacyTalkServiceClientImpl.S2(Unknown Source:28)
	at hd1.f$d.f(Unknown Source:27)
	at Zf.c$a.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at jp.naver.line.android.util.p$a.c(Unknown Source:47)
	at jp.naver.line.android.util.p$a.run(Unknown Source:31)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by areteruhiro** [comment]
2dで、トラッキングの無効の仕方を変更しています、もしトラッキング無効利用されたいなら2dをお使いになってください

**Comment by hy906040** [comment]
今の所クラッシュは発生していないですが、対応済になっている未読スイッチがオンの場合でも未読カウントが消えることがありましたので報告します。
消える場合と消えない場合があるのでなんとも言えないのですが、メッセージ受信後すぐにトークを開くと消えているように感じました。

**Comment by areteruhiro** [comment]
> 今の所クラッシュは発生していないですが、対応済になっている未読スイッチがオンの場合でも未読カウントが消えることがありましたので報告します。
> 消える場合と消えない場合があるのでなんとも言えないのですが、メッセージ受信後すぐにトークを開くと消えているように感じました。

報告ありがとうございます、精査します

**Comment by areteruhiro** [comment]
> 今の所クラッシュは発生していないですが、対応済になっている未読スイッチがオンの場合でも未読カウントが消えることがありましたので報告します。
> 消える場合と消えない場合があるのでなんとも言えないのですが、メッセージ受信後すぐにトークを開くと消えているように感じました。

再現できないですね、画面録画などをしてもらうことはできませんか

**Comment by areteruhiro** [comment]
自分も、トラッキング通信機能のブロックでクラッシュ再現できました。

**Comment by hy906040** [comment]
いつ発生するかわからないですが録画するよう心がけますね。

**Comment by areteruhiro** [comment]
> いつ発生するかわからないですが録画するよう心がけますね。

こちらも対策できる確認してみます。
録画については難しいと思うので大丈夫です
